# Generated by Django 4.2.11 on 2024-04-02 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0028_video_views_delete_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='release_year',
            field=models.PositiveSmallIntegerField(default=2024),
        ),
    ]
